[package]
name = "serial-console"
version = "0.4.0"
authors = ["Hendrik Wolff <hendrik.wolff@agdsn.me>"]
license = "MIT"
repository = "https://gitlab.com/w0lff/serial-console"
description = "A terminal program to communicate with a serial console"
edition = "2018"

[dependencies]
log = "0.4.14"
serialport = "4.0.1"
structopt = "0.3.22"
termion = "1.5.6"

[[bin]]
name = "sc"
path = "./src/main.rs"
