[package]
name = "serial-console"
version = "0.1.0"
authors = ["Hendrik Wolff hendrik.wolff@agdsn.me>"]
license = "MIT"
repository = "https://gitlab.com/w0lff/serial-console"
description = "A terminal program to communicate with a serial console"
edition = "2018"

[dependencies]
structopt = "0.3.22"

[[bin]]
name = "sc"
path = "./src/main.rs"
